name: "Create release"

on:
  workflow_dispatch::

permissions:
  pull-requests: write
  contents: write

jobs:
  main:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: build and release application
        run: |
          git config --global user.name 'lostb1t'
          git config --global user.email 'coding-mosses0z@icloud.com'
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}